### PR TITLE
Accumulo 3005 Fix for ThriftServerBindsBeforeZooKeeperLockIT

### PR DESCRIPTION
**Pull request by milleruntime**
One solution for ThriftServerBindsBeforeZooKeeperLockIT.  Modified test to look for an OK response.  It was looking for a response that no longer existed.

### CODE REVIEW

**Comment by lstav** [comment]
Thanks for fixing it! Merging in.

**Comment by lstav** [comment]
@milleruntime could you make the pull request to the ACCUMULO-MONITOR branch? That's the one that is on the Accumulo pull request. Thanks.

Edit: Nevermind, I made the pull request myself from your branch.

**Comment by lstav** [comment]
I'll try and fix it tomorrow, the pull request I did didn't do what I was expecting...

**Comment by milleruntime** [comment]
Sorry I should have made the pull request against your branch and not your master.  I can't make a clean PR against ACCUMULO-MONITOR.  Did you rebase your branch?

**Comment by lstav** [comment]
yes I did yesterday, I'll try to merge directly sometime this weekend, I added your branch as a remote, and I got some merge conflicts which I'll try to resolve. If you manage to get it into a clean PR before I comment again, feel free to do so.

**Comment by milleruntime** [comment]
I just opened a proper pull request that should be way easier: https://github.com/lstav/accumulo/pull/9

**Comment by lstav** [comment]
Much easier now haha, thanks. It is merged.

**Comment by milleruntime** [comment]
Sorry about that!  That is what I get for rushing my pull request before leaving for the day.

**Comment by lstav** [comment]
No worries, happens to all of us haha.

**Pull request merged**
