### PR TITLE
Integrate Jersey servlet into old monitor

### PR DESCRIPTION
**Pull request by ctubbsii**
This integration preserves the existing servlet which serves static resources from the classpath. We can possibly replace that static resource loader in the future, or dramatically simplify it. For now, this gets the new stuff working with the old stuff, on the same port.

### CODE REVIEW

**Comment by ctubbsii** [comment]
I merged the current master onto the branch.

**Comment by ctubbsii** [comment]
The branch needs to be rebase'd onto master. Let me know when you've done that, and I'll rebase my PR onto yours, so the diff will be smaller and more clear.

**Comment by lstav** [comment]
I just did the rebase. Thanks for the help.

**Comment by ctubbsii** [comment]
Awesome, I rebase'd my PR onto your updated branch.

**Comment by lstav** [comment]
Thanks! Will this make the REST Monitor run instead of the Old Monitor? It seems like it from what I saw on the changes, just wanted to be sure.

**Comment by ctubbsii** [comment]
Technically, this makes the REST monitor run as part of the old monitor. The old monitor will now use the new code (mostly). There are still some servlets to replace, and some other potential things to refactor for clean-up.

**Comment by lstav** [comment]
I see, thanks for the response.

**Pull request merged**
